# InfluxDB 1.x 配置

# 读取：数据中心内所有空调、环境的状态
influxdb_dc_status_data:
  host: &host "10.0.0.6"  # InfluxDB 1.x 服务器地址
  port: &port 8086         # InfluxDB 1.x 默认端口
  username: &username "admin"  # 用户名
  password: &password "Laimi@168"  # 密码
  database: "iot_origin_database"  # 数据库名称

# 写入：预测模块的输出
influxdb_prediction_data:
  host: *host
  port: *port
  username: *username
  password: *password
  database: "iot_origin_database"

# 写入：优化模块的实际输出（实际用于调控的输出）
influxdb_setting_data:
  host: *host
  port: *port
  username: *username
  password: *password
  database: "iot_origin_database"

# 写入：优化模块的参考输出
influxdb_reference_data:
  host: *host
  port: *port
  username: *username
  password: *password
  database: "iot_origin_database"