room_name: 103A信息化机房
air_conditioners:
  1F IDC机房9#空调:
    device_name: 1F IDC机房9#空调
    measurement_points:
      风机转速（%）: N2_S0_E9_A1
      水阀开度（%）: N2_S0_E9_A2
      回风湿度测量值（%）: N2_S0_E9_A3
      回风温度测量值（℃）: N2_S0_E9_A4
      风压设定点（Pa）: N2_S0_E9_A26
      回风湿度设定点（%）: N2_S0_E9_A27
      回风温度设定点（℃）: N2_S0_E9_A28
      远程平均温度设定点（℃）: N2_S0_E9_A30
      远程最高温度设定点（℃）: N2_S0_E9_A31
      远程关机报警状态: N2_S0_E9_D1
      地板溢水报警状态: N2_S0_E9_D2
      高水位报警状态: N2_S0_E9_D3
      加湿器报警状态: N2_S0_E9_D4
      电加热报警状态: N2_S0_E9_D5
      风机报警状态: N2_S0_E9_D6
      冷凝水泵报警状态: N2_S0_E9_D7
      烟感报警状态: N2_S0_E9_D8
      水流丢失报警状态: N2_S0_E9_D9
      气流丢失报警状态: N2_S0_E9_D10
      过滤网堵塞报警状态: N2_S0_E9_D11
      过滤网维护报警状态: N2_S0_E9_D12
      缺省1报警状态: N2_S0_E9_D13
      缺省2报警状态: N2_S0_E9_D14
      回风高湿报警状态: N2_S0_E9_D15
      回风低湿报警状态: N2_S0_E9_D16
      回风高温报警状态: N2_S0_E9_D17
      回风低温报警状态: N2_S0_E9_D18
      送风高温报警状态: N2_S0_E9_D19
      送风低温报警状态: N2_S0_E9_D20
      远程高温报警状态: N2_S0_E9_D21
      远程低温报警状态: N2_S0_E9_D22
      进水高温报警状态: N2_S0_E9_D23
      回风温度传感器故障报警状态: N2_S0_E9_D24
      回风湿度传感器故障报警状态: N2_S0_E9_D25
      气流温度传感器故障报警状态: N2_S0_E9_D26
      送风温度传感器故障报警状态: N2_S0_E9_D27
      远程温度传感器故障报警状态: N2_S0_E9_D28
      进水温度传感器故障报警状态: N2_S0_E9_D29
      出水温度传感器故障报警状态: N2_S0_E9_D30
      风压1传感器故障报警状态: N2_S0_E9_D31
      风压2传感器故障报警状态: N2_S0_E9_D32
      水压1传感器故障报警状态: N2_S0_E9_D33
      水压2传感器故障报警状态: N2_S0_E9_D34
      水流量传感器故障报警状态: N2_S0_E9_D35
      电源丢失报警状态: N2_S0_E9_D36
      电源过压报警状态: N2_S0_E9_D37
      电源欠压报警状态: N2_S0_E9_D38
      电源频偏报警状态: N2_S0_E9_D39
      电源缺相报警状态: N2_S0_E9_D40
      电源反相报警状态: N2_S0_E9_D41
      机组制冷状态: N2_S0_E9_D42
      机组加热状态: N2_S0_E9_D43
      机组加湿状态: N2_S0_E9_D44
      机组除湿状态: N2_S0_E9_D45
      远程关机状态: N2_S0_E9_D46
      本地关机状态: N2_S0_E9_D47
      监控关机状态: N2_S0_E9_D48
      机组运行状态: N2_S0_E9_D49
      风机控制模式: N2_S0_E9_D50
      水阀控制模式: N2_S0_E9_D51
      监控开关机状态: N2_S0_E9_D52
  1F IDC机房8#空调:
    device_name: 1F IDC机房8#空调
    measurement_points:
      风机转速（%）: N2_S0_E8_A1
      水阀开度（%）: N2_S0_E8_A2
      回风湿度测量值（%）: N2_S0_E8_A3
      回风温度测量值（℃）: N2_S0_E8_A4
      风压设定点（Pa）: N2_S0_E8_A26
      回风湿度设定点（%）: N2_S0_E8_A27
      回风温度设定点（℃）: N2_S0_E8_A28
      远程平均温度设定点（℃）: N2_S0_E8_A30
      远程最高温度设定点（℃）: N2_S0_E8_A31
      远程关机报警状态: N2_S0_E8_D1
      地板溢水报警状态: N2_S0_E8_D2
      高水位报警状态: N2_S0_E8_D3
      加湿器报警状态: N2_S0_E8_D4
      电加热报警状态: N2_S0_E8_D5
      风机报警状态: N2_S0_E8_D6
      冷凝水泵报警状态: N2_S0_E8_D7
      烟感报警状态: N2_S0_E8_D8
      水流丢失报警状态: N2_S0_E8_D9
      气流丢失报警状态: N2_S0_E8_D10
      过滤网堵塞报警状态: N2_S0_E8_D11
      过滤网维护报警状态: N2_S0_E8_D12
      缺省1报警状态: N2_S0_E8_D13
      缺省2报警状态: N2_S0_E8_D14
      回风高湿报警状态: N2_S0_E8_D15
      回风低湿报警状态: N2_S0_E8_D16
      回风高温报警状态: N2_S0_E8_D17
      回风低温报警状态: N2_S0_E8_D18
      送风高温报警状态: N2_S0_E8_D19
      送风低温报警状态: N2_S0_E8_D20
      远程高温报警状态: N2_S0_E8_D21
      远程低温报警状态: N2_S0_E8_D22
      进水高温报警状态: N2_S0_E8_D23
      回风温度传感器故障报警状态: N2_S0_E8_D24
      回风湿度传感器故障报警状态: N2_S0_E8_D25
      气流温度传感器故障报警状态: N2_S0_E8_D26
      送风温度传感器故障报警状态: N2_S0_E8_D27
      远程温度传感器故障报警状态: N2_S0_E8_D28
      进水温度传感器故障报警状态: N2_S0_E8_D29
      出水温度传感器故障报警状态: N2_S0_E8_D30
      风压1传感器故障报警状态: N2_S0_E8_D31
      风压2传感器故障报警状态: N2_S0_E8_D32
      水压1传感器故障报警状态: N2_S0_E8_D33
      水压2传感器故障报警状态: N2_S0_E8_D34
      水流量传感器故障报警状态: N2_S0_E8_D35
      电源丢失报警状态: N2_S0_E8_D36
      电源过压报警状态: N2_S0_E8_D37
      电源欠压报警状态: N2_S0_E8_D38
      电源频偏报警状态: N2_S0_E8_D39
      电源缺相报警状态: N2_S0_E8_D40
      电源反相报警状态: N2_S0_E8_D41
      机组制冷状态: N2_S0_E8_D42
      机组加热状态: N2_S0_E8_D43
      机组加湿状态: N2_S0_E8_D44
      机组除湿状态: N2_S0_E8_D45
      远程关机状态: N2_S0_E8_D46
      本地关机状态: N2_S0_E8_D47
      监控关机状态: N2_S0_E8_D48
      机组运行状态: N2_S0_E8_D49
      风机控制模式: N2_S0_E8_D50
      水阀控制模式: N2_S0_E8_D51
      监控开关机状态: N2_S0_E8_D52
  1F IDC机房7#空调:
    device_name: 1F IDC机房7#空调
    measurement_points:
      风机转速（%）: N2_S0_E7_A1
      水阀开度（%）: N2_S0_E7_A2
      回风湿度测量值（%）: N2_S0_E7_A3
      回风温度测量值（℃）: N2_S0_E7_A4
      风压设定点（Pa）: N2_S0_E7_A26
      回风湿度设定点（%）: N2_S0_E7_A27
      回风温度设定点（℃）: N2_S0_E7_A28
      远程平均温度设定点（℃）: N2_S0_E7_A30
      远程最高温度设定点（℃）: N2_S0_E7_A31
      远程关机报警状态: N2_S0_E7_D1
      地板溢水报警状态: N2_S0_E7_D2
      高水位报警状态: N2_S0_E7_D3
      加湿器报警状态: N2_S0_E7_D4
      电加热报警状态: N2_S0_E7_D5
      风机报警状态: N2_S0_E7_D6
      冷凝水泵报警状态: N2_S0_E7_D7
      烟感报警状态: N2_S0_E7_D8
      水流丢失报警状态: N2_S0_E7_D9
      气流丢失报警状态: N2_S0_E7_D10
      过滤网堵塞报警状态: N2_S0_E7_D11
      过滤网维护报警状态: N2_S0_E7_D12
      缺省1报警状态: N2_S0_E7_D13
      缺省2报警状态: N2_S0_E7_D14
      回风高湿报警状态: N2_S0_E7_D15
      回风低湿报警状态: N2_S0_E7_D16
      回风高温报警状态: N2_S0_E7_D17
      回风低温报警状态: N2_S0_E7_D18
      送风高温报警状态: N2_S0_E7_D19
      送风低温报警状态: N2_S0_E7_D20
      远程高温报警状态: N2_S0_E7_D21
      远程低温报警状态: N2_S0_E7_D22
      进水高温报警状态: N2_S0_E7_D23
      回风温度传感器故障报警状态: N2_S0_E7_D24
      回风湿度传感器故障报警状态: N2_S0_E7_D25
      气流温度传感器故障报警状态: N2_S0_E7_D26
      送风温度传感器故障报警状态: N2_S0_E7_D27
      远程温度传感器故障报警状态: N2_S0_E7_D28
      进水温度传感器故障报警状态: N2_S0_E7_D29
      出水温度传感器故障报警状态: N2_S0_E7_D30
      风压1传感器故障报警状态: N2_S0_E7_D31
      风压2传感器故障报警状态: N2_S0_E7_D32
      水压1传感器故障报警状态: N2_S0_E7_D33
      水压2传感器故障报警状态: N2_S0_E7_D34
      水流量传感器故障报警状态: N2_S0_E7_D35
      电源丢失报警状态: N2_S0_E7_D36
      电源过压报警状态: N2_S0_E7_D37
      电源欠压报警状态: N2_S0_E7_D38
      电源频偏报警状态: N2_S0_E7_D39
      电源缺相报警状态: N2_S0_E7_D40
      电源反相报警状态: N2_S0_E7_D41
      机组制冷状态: N2_S0_E7_D42
      机组加热状态: N2_S0_E7_D43
      机组加湿状态: N2_S0_E7_D44
      机组除湿状态: N2_S0_E7_D45
      远程关机状态: N2_S0_E7_D46
      本地关机状态: N2_S0_E7_D47
      监控关机状态: N2_S0_E7_D48
      机组运行状态: N2_S0_E7_D49
      风机控制模式: N2_S0_E7_D50
      水阀控制模式: N2_S0_E7_D51
      监控开关机状态: N2_S0_E7_D52
  1F IDC机房6#空调:
    device_name: 1F IDC机房6#空调
    measurement_points:
      风机转速（%）: N2_S0_E6_A1
      水阀开度（%）: N2_S0_E6_A2
      回风湿度测量值（%）: N2_S0_E6_A3
      回风温度测量值（℃）: N2_S0_E6_A4
      风压设定点（Pa）: N2_S0_E6_A26
      回风湿度设定点（%）: N2_S0_E6_A27
      回风温度设定点（℃）: N2_S0_E6_A28
      远程平均温度设定点（℃）: N2_S0_E6_A30
      远程最高温度设定点（℃）: N2_S0_E6_A31
      远程关机报警状态: N2_S0_E6_D1
      地板溢水报警状态: N2_S0_E6_D2
      高水位报警状态: N2_S0_E6_D3
      加湿器报警状态: N2_S0_E6_D4
      电加热报警状态: N2_S0_E6_D5
      风机报警状态: N2_S0_E6_D6
      冷凝水泵报警状态: N2_S0_E6_D7
      烟感报警状态: N2_S0_E6_D8
      水流丢失报警状态: N2_S0_E6_D9
      气流丢失报警状态: N2_S0_E6_D10
      过滤网堵塞报警状态: N2_S0_E6_D11
      过滤网维护报警状态: N2_S0_E6_D12
      缺省1报警状态: N2_S0_E6_D13
      缺省2报警状态: N2_S0_E6_D14
      回风高湿报警状态: N2_S0_E6_D15
      回风低湿报警状态: N2_S0_E6_D16
      回风高温报警状态: N2_S0_E6_D17
      回风低温报警状态: N2_S0_E6_D18
      送风高温报警状态: N2_S0_E6_D19
      送风低温报警状态: N2_S0_E6_D20
      远程高温报警状态: N2_S0_E6_D21
      远程低温报警状态: N2_S0_E6_D22
      进水高温报警状态: N2_S0_E6_D23
      回风温度传感器故障报警状态: N2_S0_E6_D24
      回风湿度传感器故障报警状态: N2_S0_E6_D25
      气流温度传感器故障报警状态: N2_S0_E6_D26
      送风温度传感器故障报警状态: N2_S0_E6_D27
      远程温度传感器故障报警状态: N2_S0_E6_D28
      进水温度传感器故障报警状态: N2_S0_E6_D29
      出水温度传感器故障报警状态: N2_S0_E6_D30
      风压1传感器故障报警状态: N2_S0_E6_D31
      风压2传感器故障报警状态: N2_S0_E6_D32
      水压1传感器故障报警状态: N2_S0_E6_D33
      水压2传感器故障报警状态: N2_S0_E6_D34
      水流量传感器故障报警状态: N2_S0_E6_D35
      电源丢失报警状态: N2_S0_E6_D36
      电源过压报警状态: N2_S0_E6_D37
      电源欠压报警状态: N2_S0_E6_D38
      电源频偏报警状态: N2_S0_E6_D39
      电源缺相报警状态: N2_S0_E6_D40
      电源反相报警状态: N2_S0_E6_D41
      机组制冷状态: N2_S0_E6_D42
      机组加热状态: N2_S0_E6_D43
      机组加湿状态: N2_S0_E6_D44
      机组除湿状态: N2_S0_E6_D45
      远程关机状态: N2_S0_E6_D46
      本地关机状态: N2_S0_E6_D47
      监控关机状态: N2_S0_E6_D48
      机组运行状态: N2_S0_E6_D49
      风机控制模式: N2_S0_E6_D50
      水阀控制模式: N2_S0_E6_D51
      监控开关机状态: N2_S0_E6_D52
  1F IDC机房5#空调:
    device_name: 1F IDC机房5#空调
    measurement_points:
      风机转速（%）: N2_S0_E5_A1
      水阀开度（%）: N2_S0_E5_A2
      回风湿度测量值（%）: N2_S0_E5_A3
      回风温度测量值（℃）: N2_S0_E5_A4
      风压设定点（Pa）: N2_S0_E5_A26
      回风湿度设定点（%）: N2_S0_E5_A27
      回风温度设定点（℃）: N2_S0_E5_A28
      远程平均温度设定点（℃）: N2_S0_E5_A30
      远程最高温度设定点（℃）: N2_S0_E5_A31
      远程关机报警状态: N2_S0_E5_D1
      地板溢水报警状态: N2_S0_E5_D2
      高水位报警状态: N2_S0_E5_D3
      加湿器报警状态: N2_S0_E5_D4
      电加热报警状态: N2_S0_E5_D5
      风机报警状态: N2_S0_E5_D6
      冷凝水泵报警状态: N2_S0_E5_D7
      烟感报警状态: N2_S0_E5_D8
      水流丢失报警状态: N2_S0_E5_D9
      气流丢失报警状态: N2_S0_E5_D10
      过滤网堵塞报警状态: N2_S0_E5_D11
      过滤网维护报警状态: N2_S0_E5_D12
      缺省1报警状态: N2_S0_E5_D13
      缺省2报警状态: N2_S0_E5_D14
      回风高湿报警状态: N2_S0_E5_D15
      回风低湿报警状态: N2_S0_E5_D16
      回风高温报警状态: N2_S0_E5_D17
      回风低温报警状态: N2_S0_E5_D18
      送风高温报警状态: N2_S0_E5_D19
      送风低温报警状态: N2_S0_E5_D20
      远程高温报警状态: N2_S0_E5_D21
      远程低温报警状态: N2_S0_E5_D22
      进水高温报警状态: N2_S0_E5_D23
      回风温度传感器故障报警状态: N2_S0_E5_D24
      回风湿度传感器故障报警状态: N2_S0_E5_D25
      气流温度传感器故障报警状态: N2_S0_E5_D26
      送风温度传感器故障报警状态: N2_S0_E5_D27
      远程温度传感器故障报警状态: N2_S0_E5_D28
      进水温度传感器故障报警状态: N2_S0_E5_D29
      出水温度传感器故障报警状态: N2_S0_E5_D30
      风压1传感器故障报警状态: N2_S0_E5_D31
      风压2传感器故障报警状态: N2_S0_E5_D32
      水压1传感器故障报警状态: N2_S0_E5_D33
      水压2传感器故障报警状态: N2_S0_E5_D34
      水流量传感器故障报警状态: N2_S0_E5_D35
      电源丢失报警状态: N2_S0_E5_D36
      电源过压报警状态: N2_S0_E5_D37
      电源欠压报警状态: N2_S0_E5_D38
      电源频偏报警状态: N2_S0_E5_D39
      电源缺相报警状态: N2_S0_E5_D40
      电源反相报警状态: N2_S0_E5_D41
      机组制冷状态: N2_S0_E5_D42
      机组加热状态: N2_S0_E5_D43
      机组加湿状态: N2_S0_E5_D44
      机组除湿状态: N2_S0_E5_D45
      远程关机状态: N2_S0_E5_D46
      本地关机状态: N2_S0_E5_D47
      监控关机状态: N2_S0_E5_D48
      机组运行状态: N2_S0_E5_D49
      风机控制模式: N2_S0_E5_D50
      水阀控制模式: N2_S0_E5_D51
      监控开关机状态: N2_S0_E5_D52
  1F IDC机房4#空调:
    device_name: 1F IDC机房4#空调
    measurement_points:
      风机转速（%）: N2_S0_E4_A1
      水阀开度（%）: N2_S0_E4_A2
      回风湿度测量值（%）: N2_S0_E4_A3
      回风温度测量值（℃）: N2_S0_E4_A4
      风压设定点（Pa）: N2_S0_E4_A26
      回风湿度设定点（%）: N2_S0_E4_A27
      回风温度设定点（℃）: N2_S0_E4_A28
      远程平均温度设定点（℃）: N2_S0_E4_A30
      远程最高温度设定点（℃）: N2_S0_E4_A31
      远程关机报警状态: N2_S0_E4_D1
      地板溢水报警状态: N2_S0_E4_D2
      高水位报警状态: N2_S0_E4_D3
      加湿器报警状态: N2_S0_E4_D4
      电加热报警状态: N2_S0_E4_D5
      风机报警状态: N2_S0_E4_D6
      冷凝水泵报警状态: N2_S0_E4_D7
      烟感报警状态: N2_S0_E4_D8
      水流丢失报警状态: N2_S0_E4_D9
      气流丢失报警状态: N2_S0_E4_D10
      过滤网堵塞报警状态: N2_S0_E4_D11
      过滤网维护报警状态: N2_S0_E4_D12
      缺省1报警状态: N2_S0_E4_D13
      缺省2报警状态: N2_S0_E4_D14
      回风高湿报警状态: N2_S0_E4_D15
      回风低湿报警状态: N2_S0_E4_D16
      回风高温报警状态: N2_S0_E4_D17
      回风低温报警状态: N2_S0_E4_D18
      送风高温报警状态: N2_S0_E4_D19
      送风低温报警状态: N2_S0_E4_D20
      远程高温报警状态: N2_S0_E4_D21
      远程低温报警状态: N2_S0_E4_D22
      进水高温报警状态: N2_S0_E4_D23
      回风温度传感器故障报警状态: N2_S0_E4_D24
      回风湿度传感器故障报警状态: N2_S0_E4_D25
      气流温度传感器故障报警状态: N2_S0_E4_D26
      送风温度传感器故障报警状态: N2_S0_E4_D27
      远程温度传感器故障报警状态: N2_S0_E4_D28
      进水温度传感器故障报警状态: N2_S0_E4_D29
      出水温度传感器故障报警状态: N2_S0_E4_D30
      风压1传感器故障报警状态: N2_S0_E4_D31
      风压2传感器故障报警状态: N2_S0_E4_D32
      水压1传感器故障报警状态: N2_S0_E4_D33
      水压2传感器故障报警状态: N2_S0_E4_D34
      水流量传感器故障报警状态: N2_S0_E4_D35
      电源丢失报警状态: N2_S0_E4_D36
      电源过压报警状态: N2_S0_E4_D37
      电源欠压报警状态: N2_S0_E4_D38
      电源频偏报警状态: N2_S0_E4_D39
      电源缺相报警状态: N2_S0_E4_D40
      电源反相报警状态: N2_S0_E4_D41
      机组制冷状态: N2_S0_E4_D42
      机组加热状态: N2_S0_E4_D43
      机组加湿状态: N2_S0_E4_D44
      机组除湿状态: N2_S0_E4_D45
      远程关机状态: N2_S0_E4_D46
      本地关机状态: N2_S0_E4_D47
      监控关机状态: N2_S0_E4_D48
      机组运行状态: N2_S0_E4_D49
      风机控制模式: N2_S0_E4_D50
      水阀控制模式: N2_S0_E4_D51
      监控开关机状态: N2_S0_E4_D52
  1F IDC机房3#空调:
    device_name: 1F IDC机房3#空调
    measurement_points:
      风机转速（%）: N2_S0_E3_A1
      水阀开度（%）: N2_S0_E3_A2
      回风湿度测量值（%）: N2_S0_E3_A3
      回风温度测量值（℃）: N2_S0_E3_A4
      风压设定点（Pa）: N2_S0_E3_A26
      回风湿度设定点（%）: N2_S0_E3_A27
      回风温度设定点（℃）: N2_S0_E3_A28
      远程平均温度设定点（℃）: N2_S0_E3_A30
      远程最高温度设定点（℃）: N2_S0_E3_A31
      远程关机报警状态: N2_S0_E3_D1
      地板溢水报警状态: N2_S0_E3_D2
      高水位报警状态: N2_S0_E3_D3
      加湿器报警状态: N2_S0_E3_D4
      电加热报警状态: N2_S0_E3_D5
      风机报警状态: N2_S0_E3_D6
      冷凝水泵报警状态: N2_S0_E3_D7
      烟感报警状态: N2_S0_E3_D8
      水流丢失报警状态: N2_S0_E3_D9
      气流丢失报警状态: N2_S0_E3_D10
      过滤网堵塞报警状态: N2_S0_E3_D11
      过滤网维护报警状态: N2_S0_E3_D12
      缺省1报警状态: N2_S0_E3_D13
      缺省2报警状态: N2_S0_E3_D14
      回风高湿报警状态: N2_S0_E3_D15
      回风低湿报警状态: N2_S0_E3_D16
      回风高温报警状态: N2_S0_E3_D17
      回风低温报警状态: N2_S0_E3_D18
      送风高温报警状态: N2_S0_E3_D19
      送风低温报警状态: N2_S0_E3_D20
      远程高温报警状态: N2_S0_E3_D21
      远程低温报警状态: N2_S0_E3_D22
      进水高温报警状态: N2_S0_E3_D23
      回风温度传感器故障报警状态: N2_S0_E3_D24
      回风湿度传感器故障报警状态: N2_S0_E3_D25
      气流温度传感器故障报警状态: N2_S0_E3_D26
      送风温度传感器故障报警状态: N2_S0_E3_D27
      远程温度传感器故障报警状态: N2_S0_E3_D28
      进水温度传感器故障报警状态: N2_S0_E3_D29
      出水温度传感器故障报警状态: N2_S0_E3_D30
      风压1传感器故障报警状态: N2_S0_E3_D31
      风压2传感器故障报警状态: N2_S0_E3_D32
      水压1传感器故障报警状态: N2_S0_E3_D33
      水压2传感器故障报警状态: N2_S0_E3_D34
      水流量传感器故障报警状态: N2_S0_E3_D35
      电源丢失报警状态: N2_S0_E3_D36
      电源过压报警状态: N2_S0_E3_D37
      电源欠压报警状态: N2_S0_E3_D38
      电源频偏报警状态: N2_S0_E3_D39
      电源缺相报警状态: N2_S0_E3_D40
      电源反相报警状态: N2_S0_E3_D41
      机组制冷状态: N2_S0_E3_D42
      机组加热状态: N2_S0_E3_D43
      机组加湿状态: N2_S0_E3_D44
      机组除湿状态: N2_S0_E3_D45
      远程关机状态: N2_S0_E3_D46
      本地关机状态: N2_S0_E3_D47
      监控关机状态: N2_S0_E3_D48
      机组运行状态: N2_S0_E3_D49
      风机控制模式: N2_S0_E3_D50
      水阀控制模式: N2_S0_E3_D51
      监控开关机状态: N2_S0_E3_D52
  1F IDC机房2#空调:
    device_name: 1F IDC机房2#空调
    measurement_points:
      风机转速（%）: N2_S0_E2_A1
      水阀开度（%）: N2_S0_E2_A2
      回风湿度测量值（%）: N2_S0_E2_A3
      回风温度测量值（℃）: N2_S0_E2_A4
      风压设定点（Pa）: N2_S0_E2_A26
      回风湿度设定点（%）: N2_S0_E2_A27
      回风温度设定点（℃）: N2_S0_E2_A28
      远程平均温度设定点（℃）: N2_S0_E2_A30
      远程最高温度设定点（℃）: N2_S0_E2_A31
      远程关机报警状态: N2_S0_E2_D1
      地板溢水报警状态: N2_S0_E2_D2
      高水位报警状态: N2_S0_E2_D3
      加湿器报警状态: N2_S0_E2_D4
      电加热报警状态: N2_S0_E2_D5
      风机报警状态: N2_S0_E2_D6
      冷凝水泵报警状态: N2_S0_E2_D7
      烟感报警状态: N2_S0_E2_D8
      水流丢失报警状态: N2_S0_E2_D9
      气流丢失报警状态: N2_S0_E2_D10
      过滤网堵塞报警状态: N2_S0_E2_D11
      过滤网维护报警状态: N2_S0_E2_D12
      缺省1报警状态: N2_S0_E2_D13
      缺省2报警状态: N2_S0_E2_D14
      回风高湿报警状态: N2_S0_E2_D15
      回风低湿报警状态: N2_S0_E2_D16
      回风高温报警状态: N2_S0_E2_D17
      回风低温报警状态: N2_S0_E2_D18
      送风高温报警状态: N2_S0_E2_D19
      送风低温报警状态: N2_S0_E2_D20
      远程高温报警状态: N2_S0_E2_D21
      远程低温报警状态: N2_S0_E2_D22
      进水高温报警状态: N2_S0_E2_D23
      回风温度传感器故障报警状态: N2_S0_E2_D24
      回风湿度传感器故障报警状态: N2_S0_E2_D25
      气流温度传感器故障报警状态: N2_S0_E2_D26
      送风温度传感器故障报警状态: N2_S0_E2_D27
      远程温度传感器故障报警状态: N2_S0_E2_D28
      进水温度传感器故障报警状态: N2_S0_E2_D29
      出水温度传感器故障报警状态: N2_S0_E2_D30
      风压1传感器故障报警状态: N2_S0_E2_D31
      风压2传感器故障报警状态: N2_S0_E2_D32
      水压1传感器故障报警状态: N2_S0_E2_D33
      水压2传感器故障报警状态: N2_S0_E2_D34
      水流量传感器故障报警状态: N2_S0_E2_D35
      电源丢失报警状态: N2_S0_E2_D36
      电源过压报警状态: N2_S0_E2_D37
      电源欠压报警状态: N2_S0_E2_D38
      电源频偏报警状态: N2_S0_E2_D39
      电源缺相报警状态: N2_S0_E2_D40
      电源反相报警状态: N2_S0_E2_D41
      机组制冷状态: N2_S0_E2_D42
      机组加热状态: N2_S0_E2_D43
      机组加湿状态: N2_S0_E2_D44
      机组除湿状态: N2_S0_E2_D45
      远程关机状态: N2_S0_E2_D46
      本地关机状态: N2_S0_E2_D47
      监控关机状态: N2_S0_E2_D48
      机组运行状态: N2_S0_E2_D49
      风机控制模式: N2_S0_E2_D50
      水阀控制模式: N2_S0_E2_D51
      监控开关机状态: N2_S0_E2_D52
  1F IDC机房1#空调:
    device_name: 1F IDC机房1#空调
    measurement_points:
      风机转速（%）: N2_S0_E1_A1
      水阀开度（%）: N2_S0_E1_A2
      回风湿度测量值（%）: N2_S0_E1_A3
      回风温度测量值（℃）: N2_S0_E1_A4
      风压设定点（Pa）: N2_S0_E1_A26
      回风湿度设定点（%）: N2_S0_E1_A27
      回风温度设定点（℃）: N2_S0_E1_A28
      远程平均温度设定点（℃）: N2_S0_E1_A30
      远程最高温度设定点（℃）: N2_S0_E1_A31
      远程关机报警状态: N2_S0_E1_D1
      地板溢水报警状态: N2_S0_E1_D2
      高水位报警状态: N2_S0_E1_D3
      加湿器报警状态: N2_S0_E1_D4
      电加热报警状态: N2_S0_E1_D5
      风机报警状态: N2_S0_E1_D6
      冷凝水泵报警状态: N2_S0_E1_D7
      烟感报警状态: N2_S0_E1_D8
      水流丢失报警状态: N2_S0_E1_D9
      气流丢失报警状态: N2_S0_E1_D10
      过滤网堵塞报警状态: N2_S0_E1_D11
      过滤网维护报警状态: N2_S0_E1_D12
      缺省1报警状态: N2_S0_E1_D13
      缺省2报警状态: N2_S0_E1_D14
      回风高湿报警状态: N2_S0_E1_D15
      回风低湿报警状态: N2_S0_E1_D16
      回风高温报警状态: N2_S0_E1_D17
      回风低温报警状态: N2_S0_E1_D18
      送风高温报警状态: N2_S0_E1_D19
      送风低温报警状态: N2_S0_E1_D20
      远程高温报警状态: N2_S0_E1_D21
      远程低温报警状态: N2_S0_E1_D22
      进水高温报警状态: N2_S0_E1_D23
      回风温度传感器故障报警状态: N2_S0_E1_D24
      回风湿度传感器故障报警状态: N2_S0_E1_D25
      气流温度传感器故障报警状态: N2_S0_E1_D26
      送风温度传感器故障报警状态: N2_S0_E1_D27
      远程温度传感器故障报警状态: N2_S0_E1_D28
      进水温度传感器故障报警状态: N2_S0_E1_D29
      出水温度传感器故障报警状态: N2_S0_E1_D30
      风压1传感器故障报警状态: N2_S0_E1_D31
      风压2传感器故障报警状态: N2_S0_E1_D32
      水压1传感器故障报警状态: N2_S0_E1_D33
      水压2传感器故障报警状态: N2_S0_E1_D34
      水流量传感器故障报警状态: N2_S0_E1_D35
      电源丢失报警状态: N2_S0_E1_D36
      电源过压报警状态: N2_S0_E1_D37
      电源欠压报警状态: N2_S0_E1_D38
      电源频偏报警状态: N2_S0_E1_D39
      电源缺相报警状态: N2_S0_E1_D40
      电源反相报警状态: N2_S0_E1_D41
      机组制冷状态: N2_S0_E1_D42
      机组加热状态: N2_S0_E1_D43
      机组加湿状态: N2_S0_E1_D44
      机组除湿状态: N2_S0_E1_D45
      远程关机状态: N2_S0_E1_D46
      本地关机状态: N2_S0_E1_D47
      监控关机状态: N2_S0_E1_D48
      机组运行状态: N2_S0_E1_D49
      风机控制模式: N2_S0_E1_D50
      水阀控制模式: N2_S0_E1_D51
      监控开关机状态: N2_S0_E1_D52
sensors:
  temperature_sensor_uid:
  - a7217828_ed16_4ffa_b789_04ada92a2e75
  - a38944a0_b951_45b2_a13c_13a6fa9223e4
  - 4fe07996_cd59_4771_ab80_bab15210849b
  - 44686a4e_336a_471f_9f04_abfe29f12c8a
  - 0ab54859_d564_4e3d_9810_2d74a26d007d
  - f50dd4c9_c782_4c40_81e6_14dcfd755436
  - bdb38c2a_f0c6_49c0_b62a_d4e0fc5fd0ea
  - a10310ed_ff3a_4bdf_b02e_0362f5808958
  - 07bb7d1d_b635_4ca9_909c_7bdaf3ceab10
  - be578260_b5e1_4e29_888f_4ba9d2c1b138
  - ad0a96f7_8d56_4120_b0fd_666f6419da54
  - N2_S0_E102_A1
  - N2_S0_E101_A1
  - N2_S0_E100_A1
  - N2_S0_E99_A1
  - N2_S0_E98_A1
  - N2_S0_E97_A1
  - N2_S0_E96_A1
  - N2_S0_E95_A1
  - N2_S0_E94_A1
  - N2_S0_E93_A1
  - N2_S0_E92_A1
  - N2_S0_E91_A1
  - N2_S0_E90_A1
  - N2_S0_E89_A1
  - N2_S0_E88_A1
  - N2_S0_E87_A1
  - N2_S0_E86_A1
  - N2_S0_E85_A1
  - N2_S0_E84_A1
  - N2_S0_E83_A1
  - N2_S0_E82_A1
  - N2_S0_E81_A1
  humidity_sensor_uid:
  - 52664cb3_a254_46c0_9674_777ef3b68793
  - 600edf85_f3ec_46e5_a811_855f82ae07f4
  - b111676c_bfed_4fca_a23e_91774e9736fa
  - 24e69074_556e_421e_88bc_d983f21e2a46
  - 25c42ff2_2278_42ca_b97c_43f82cf29737
  - dd6f7451_7a3d_4656_97ef_b350af38491a
  - b3582d8f_390a_4db6_8f42_68be2cad1339
  - 0dc718ed_ea4c_4d82_be43_6d94b9943fa7
  - e8700958_d7b7_4050_874d_294fbe149531
  - 8e318fc0_0003_43c3_8817_0920307d4e1a
  - 50811f02_536c_4bdb_88f7_1769d6110ea1
  - N2_S0_E102_A2
  - N2_S0_E101_A2
  - N2_S0_E100_A2
  - N2_S0_E99_A2
  - N2_S0_E98_A2
  - N2_S0_E97_A2
  - N2_S0_E96_A2
  - N2_S0_E95_A2
  - N2_S0_E94_A2
  - N2_S0_E93_A2
  - N2_S0_E92_A2
  - N2_S0_E91_A2
  - N2_S0_E90_A2
  - N2_S0_E89_A2
  - N2_S0_E88_A2
  - N2_S0_E87_A2
  - N2_S0_E86_A2
  - N2_S0_E85_A2
  - N2_S0_E84_A2
  - N2_S0_E83_A2
  - N2_S0_E82_A2
  - N2_S0_E81_A2
